export const breadcrumbMap: Record<string, string> = {
  dashboard: "Dashboard",
  investments: "Investimentos",
  assets: "Patrimônios",
  purposes: "Propósitos",
  institutions: "Instituições",
  users: "Usuários",
  finance: "Financeiro",
  "lancamento-ia": "Lançar via IA",
  payables: "Contas a pagar",
  receivables: "Contas a receber",
  accounts: "Contas",
  categories: "Categorias",
  "credit-cards": "Cartões de crédito",
};
