export const breadcrumbMap: Record<string, string> = {
  dashboard: "Dashboard",
  tarefas: "Tarefas",
  conquistas: "Conquistas",
  relatorios: "Relatórios",
  investments: "Investimentos",
  assets: "Patrimônios",
  purposes: "Propósitos",
  institutions: "Instituições",
  users: "Usuários",
  finance: "Financeiro",
  reports: "Relatórios",
  "plano-1-milhao": "Plano 1 Milhão",
  "lancamento-ia": "Lançar via IA",
  payables: "Contas a pagar",
  receivables: "Contas a receber",
  acertos: "Acertos",
  accounts: "Contas",
  categories: "Categorias",
  "credit-cards": "Cartões de crédito",
  consorcios: "Consórcios",
  whatsapp: "WhatsApp",
  conversas: "Conversas",
  sugestoes: "Sugestões",
};
